eureka:
  client:
    serviceUrl:
      defaultZone: http://codefanpc:10080/eureka/

server:
  port: 10081

spring:
  application:
    name: SERVICE-FRAMEWORK
  datasource:
    url: jdbc:mysql://192.168.128.32:3306/frameworkdb?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: framework
    password: framework
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      max-wait-millis: 10000
      max-idle: 15
      initial-size: 10
      validation-query: SELECT 1
      connection-properties: characterEncoding=utf8

