eureka:
  client:
    serviceUrl:
      defaultZone: http://codefanpc:10080/eureka/

server:
  port: 10085

spring:
  application:
    name: CLOUD-DEMO
  datasource:
    url: jdbc:mysql://192.168.128.32:3306/frameworkdb?useUnicode=true&characterEncoding=utf-8

jdbc:
  url:

#\u7CFB\u7EDF\u5C5E\u6027
app:
  home: /D/Projects/RunData/ip_home

#\u662F\u5426\u5F00\u653E\u5B9E\u65BD\u4EBA\u5458\u5165\u53E3
deploy:
  enabled: false

#\u5355\u70B9\u767B\u5F55\u76F8\u5173\u914D\u7F6E\u4FE1\u606F
cas:
  sso: false
  home: https://zou_wy:8443/centit-cas

#\u767B\u5F55\u6210\u529F\u540E\u7684\u9996\u9875
local:
  home: http://zouwuyangpc:8084/product-ip
  firstpage: /system/mainframe/index
