eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10080/eureka/

server:
  port: 10088

spring:
  application:
    name: GATEWAY-SERVICE
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.128.32:3306/frameworkdb?useUnicode=true&characterEncoding=utf-8
    username: framework
    password: framework
    dbcp2:
      max-wait-millis: 10000
      max-idle: 15
      initial-size: 10
      validation-query: SELECT 1
      connection-properties: characterEncoding=utf8

zuul:
  routes:
    api-system:
      path: /system/**
      serviceId: FRAMEWORK-SERVICE
    api-auth:
      path: /auth/**
      serviceId: AUTHORIZE-SERVICE
    api-workflow:
      path: /workflow/**
      serviceId: WORKFLOW-SERVICE
    api-demo:
      path: /demo/**
      serviceId: CLOUD-DEMO

#框架相关的表主键生成规制， 目前关联的就是 userinfo 和 uintinfo 两个表
#default value {"prefix":"U","length":8,"pad":"0"}
framework:
  userinfo:
    id:
      generator: \{"length":1\}
#default value {"prefix":"D","length":6,"pad":"0"}
  unitinfo:
    id:
      generator: \{"length":1\}
  roleinfo:
    id:
      generator: \{"length":1\}

session:
  redis:
    host: 192.168.134.9
    port: 6379

filter:
  rest:
    context:
      check:
        correlation: false
        user: false

security:
  login:
    cas:
      localHome:
      casHome:
    success:
      write-log: true
      regist-token: false
      target-url: /
    failure:
      write-log: false
      target-url: /system/mainframe/login/error
    captcha:
      check-time: 0
      check-type: 0
    retry:
      check-type: H
      max-try-times: 0
      lock-minites: 10
      check-time-interval: 3
  logout:
    target-url: /system/mainframe/login
  access:
    enable-anonymous: false
    resource-must-audited: false
  http:
    csrf-enable: false
    filter-continue-authentication: false
    x-frame-options-mode: deny

