eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10080/eureka/

server:
  port: 10089

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      label: master
      server:
        git:
          uri: http://gitlab.centit.com/gitlab/ctm/centit-framework-cloud.git
          search-paths: config-server/respo
          username: accounts
          password: yhs@yhs1

#应用监控设置
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
