eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10080/eureka/

server:
  port: 10088

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/ndxt/centit-framework-cloud.git
          search-paths: config-server/respo
          username: accounts
          password: yhs@yhs1

