eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:10080/eureka/

server:
  port: 10089

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      label: master
      server:
        git:
          uri: http://gitlab.centit.com/gitlab/ctm/centit-framework-cloud.git
          search-paths: config-server/respo
          username: accounts
          password: yhs@yhs1

